table executive_summary
	lineageTag: 04577bdb-82fb-5f8e-b75d-3ae15189bc4b

	column kpi
		dataType: string
		lineageTag: 7a1f071f-2253-5ab2-b640-6dc0dc4c494f
		summarizeBy: none
		sourceColumn: kpi

	column value
		dataType: double
		formatString: \$#,0.00
		lineageTag: 25cef3bd-99aa-52b7-ac23-58cb0928bfff
		summarizeBy: sum
		sourceColumn: value

	column unit
		dataType: string
		lineageTag: 50b194d0-a789-513d-8feb-704989a15282
		summarizeBy: none
		sourceColumn: unit

	column note
		dataType: string
		lineageTag: 51ec1b21-d01b-50c6-86fd-44814baa210d
		summarizeBy: none
		sourceColumn: note

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: b48fef2d-3abc-5a93-837d-c6b0a695b7bf
		summarizeBy: sum
		sourceColumn: fiscal_year

	column sort_order
		dataType: string
		lineageTag: ffbf5088-d562-5082-8e36-10161f9c3ed2
		summarizeBy: none
		sourceColumn: sort_order

	partition executive_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\executive_summary.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"kpi", type text}, {"value", type number}, {"unit", type text}, {"note", type text}, {"fiscal_year", Int64.Type}, {"sort_order", type text}})
				in
				    Typed
