table guardrail_summary
	lineageTag: bff03ccc-c4b4-5803-abbc-93f7a10961dd

	column code
		dataType: string
		lineageTag: f2074fd5-ba55-5c6c-a831-222a13ef4d10
		summarizeBy: none
		sourceColumn: code
		sortByColumn: severity

	column count
		dataType: int64
		formatString: 0
		lineageTag: dc83da48-127e-53b2-b116-23900ed61d78
		summarizeBy: sum
		sourceColumn: count

	column margin_at_risk
		dataType: double
		formatString: \$#,0.00
		lineageTag: ff7dc9d6-37d5-56ea-be63-91c0ce22389f
		summarizeBy: sum
		sourceColumn: margin_at_risk

	column severity
		dataType: int64
		formatString: 0
		lineageTag: 54c8ae33-f543-5b9d-bae8-43c9831e9a16
		summarizeBy: sum
		sourceColumn: severity

	column alert
		dataType: string
		lineageTag: 914b7524-1d2b-59fe-9d5c-125726fc845a
		summarizeBy: none
		sourceColumn: alert
		sortByColumn: alert_rank

	column alert_rank
		dataType: int64
		formatString: 0
		lineageTag: 301ecfbb-b7d1-5a80-978a-d8d933aec730
		summarizeBy: none
		sourceColumn: alert_rank

	column action
		dataType: string
		lineageTag: bc581edd-c083-59e5-9791-906f6f25a310
		summarizeBy: none
		sourceColumn: action

	partition guardrail_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\guardrail_summary.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"code", type text}, {"count", Int64.Type}, {"margin_at_risk", type number}, {"severity", Int64.Type}, {"alert", type text}, {"alert_rank", Int64.Type}, {"action", type text}})
				in
				    Typed
