table price_waterfall
	lineageTag: a337cf31-3ced-513f-a89b-39ef142ad7d6

	column scope
		dataType: string
		lineageTag: 666f52c5-cf28-55ff-aab1-5e1a676a3d8d
		summarizeBy: none
		sourceColumn: scope

	column dimension
		dataType: string
		lineageTag: 83a621b0-4444-559c-b61b-8a6d143b48b5
		summarizeBy: none
		sourceColumn: dimension

	column member
		dataType: string
		lineageTag: d5fe0320-bfd5-5ad1-bb0c-df894d3f1326
		summarizeBy: none
		sourceColumn: member

	column step
		dataType: string
		lineageTag: 72a3d418-2572-53df-9c6f-5087b77dbe94
		summarizeBy: none
		sourceColumn: step

	column kind
		dataType: string
		lineageTag: eafb3cb0-dfb4-5fac-a50e-6cfe1d36f93d
		summarizeBy: none
		sourceColumn: kind

	column amount
		dataType: double
		formatString: \$#,0.00
		lineageTag: 04356dc5-e65f-5d14-b139-ed3f994163b1
		summarizeBy: sum
		sourceColumn: amount

	column running
		dataType: double
		formatString: #,0.00
		lineageTag: 42a62bd4-f2a0-56df-8730-48f210feb5d0
		summarizeBy: sum
		sourceColumn: running

	column bucket
		dataType: string
		lineageTag: 96f044e8-8463-54a5-946e-66272bb32dd2
		summarizeBy: none
		sourceColumn: bucket

	column sort_order
		dataType: string
		lineageTag: 88f0a2d8-8fdc-5e5b-bad5-88f611995991
		summarizeBy: none
		sourceColumn: sort_order

	column delta
		dataType: double
		formatString: #,0.00
		lineageTag: 3cebdb38-7e26-53ba-b7f4-348a936e2c90
		summarizeBy: sum
		sourceColumn: delta

	partition price_waterfall = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\price_waterfall.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"scope", type text}, {"dimension", type text}, {"member", type text}, {"step", type text}, {"kind", type text}, {"amount", type number}, {"running", type number}, {"bucket", type text}, {"sort_order", type text}, {"delta", type number}})
				in
				    Typed
