table waterfall_monthly
	lineageTag: 9fd203e5-1064-56ba-ba3c-f147e37cb26a

	column month
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c23775ab-31f8-5728-8f04-7f2df37005f6
		summarizeBy: none
		sourceColumn: month

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: ec02ef0d-8d9c-50df-93f8-346e77417cf0
		summarizeBy: sum
		sourceColumn: fiscal_year

	column list_value
		dataType: double
		formatString: \$#,0.00
		lineageTag: 4f563ef6-509d-59fc-a33e-aebb882e829d
		summarizeBy: sum
		sourceColumn: list_value

	column invoice_revenue
		dataType: double
		formatString: \$#,0.00
		lineageTag: 0e51be2c-781e-5d48-871d-52ac3b18aecb
		summarizeBy: sum
		sourceColumn: invoice_revenue

	column pocket_revenue
		dataType: double
		formatString: \$#,0.00
		lineageTag: 4bbe7029-7d56-5ae8-82f7-c0736a220a8b
		summarizeBy: sum
		sourceColumn: pocket_revenue

	column cogs
		dataType: double
		formatString: #,0.00
		lineageTag: 5de79b00-0f00-5ab7-99a1-e8e7132ac00b
		summarizeBy: sum
		sourceColumn: cogs

	column quantity_units
		dataType: double
		formatString: #,0
		lineageTag: a02d7377-3942-5832-bacb-9f205e143e43
		summarizeBy: sum
		sourceColumn: quantity_units

	column net_revenue
		dataType: double
		formatString: \$#,0.00
		lineageTag: 45db765f-63e9-5b90-ab7f-04e636b3de2f
		summarizeBy: sum
		sourceColumn: net_revenue

	column pocket_margin
		dataType: double
		formatString: \$#,0.00
		lineageTag: 689301b0-20a6-5182-93e2-bef8f427f312
		summarizeBy: sum
		sourceColumn: pocket_margin

	column leakage_pct
		dataType: double
		formatString: 0.0%
		lineageTag: 05ece34e-ee65-5d44-bf10-623f94386208
		summarizeBy: sum
		sourceColumn: leakage_pct

	column pocket_margin_pct
		dataType: double
		formatString: 0.0%
		lineageTag: 285db959-4700-5e41-ade5-1cfe4bfe325c
		summarizeBy: sum
		sourceColumn: pocket_margin_pct

	column realised_price_unit
		dataType: double
		formatString: \$#,0.00
		lineageTag: 9396b253-bef7-521b-95c6-d007169db4e9
		summarizeBy: sum
		sourceColumn: realised_price_unit

	partition waterfall_monthly = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\waterfall_monthly.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"fiscal_year", Int64.Type}, {"list_value", type number}, {"invoice_revenue", type number}, {"pocket_revenue", type number}, {"cogs", type number}, {"quantity_units", type number}, {"net_revenue", type number}, {"pocket_margin", type number}, {"leakage_pct", type number}, {"pocket_margin_pct", type number}, {"realised_price_unit", type number}})
				in
				    Typed
